name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  REGISTRY: gitea.dredre.net:5005
  IMAGE_NAME: go-transit-group
  GITEA_URL: https://gitea.dredre.net

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          # Install git and clone the repository
          echo "Installing git..."
          apt-get update && apt-get install -y git
          
          echo "Cloning repository..."
          git clone https://gitea.dredre.net/dre/go-transit-group.git .
          
          echo "Checking out commit: ${{ gitea.sha }}"
          git checkout ${{ gitea.sha }}
          
          # Verify we have the expected files
          echo "Verifying checkout..."
          ls -la
          
          if [ -f "package.json" ]; then
            echo "✅ Found package.json - code checkout successful"
            echo "Repository contents:"
            ls -la
          else
            echo "❌ package.json not found - checkout failed"
            echo "Current directory: $(pwd)"
            echo "Contents:"
            ls -la
            exit 1
          fi
          
          # Show git information
          echo "Git information:"
          git log --oneline -1
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Setup Node.js
        run: |
          # Install Node.js 20 using NodeSource repository
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Lint and type check failed!"
          echo "Workflow: ${{ gitea.workflow }}"
          echo "Repository: ${{ gitea.repository }}"
          echo "Branch: ${{ gitea.ref_name }}"
          echo "Commit: ${{ gitea.sha }}"

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    steps:
      - name: Checkout code
        run: |
          # Install git and clone the repository
          echo "Installing git..."
          apt-get update && apt-get install -y git
          
          echo "Cloning repository..."
          git clone https://gitea.dredre.net/dre/go-transit-group.git .
          
          echo "Checking out commit: ${{ gitea.sha }}"
          git checkout ${{ gitea.sha }}
          
          # Verify we have the expected files
          echo "Verifying checkout..."
          ls -la
          
          if [ -f "package.json" ]; then
            echo "✅ Found package.json - code checkout successful"
            echo "Repository contents:"
            ls -la
          else
            echo "❌ package.json not found - checkout failed"
            echo "Current directory: $(pwd)"
            echo "Contents:"
            ls -la
            exit 1
          fi
          
          # Show git information
          echo "Git information:"
          git log --oneline -1
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Setup Node.js
        run: |
          # Install Node.js 20 using NodeSource repository
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          # Use stub values for build-time env vars
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Upload build artifacts
        run: |
          # Create artifacts directory
          mkdir -p /tmp/artifacts
          cp -r .next /tmp/artifacts/build-output
          echo "Build artifacts saved to /tmp/artifacts/build-output"

      - name: Notify on build failure
        if: failure()
        run: |
          echo "❌ Build failed!"
          echo "Workflow: ${{ gitea.workflow }}"
          echo "Repository: ${{ gitea.repository }}"
          echo "Branch: ${{ gitea.ref_name }}"
          echo "Commit: ${{ gitea.sha }}"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    steps:
      - name: Checkout code
        run: |
          # Install git and clone the repository
          echo "Installing git..."
          apt-get update && apt-get install -y git
          
          echo "Cloning repository..."
          git clone https://gitea.dredre.net/dre/go-transit-group.git .
          
          echo "Checking out commit: ${{ gitea.sha }}"
          git checkout ${{ gitea.sha }}
          
          # Verify we have the expected files
          echo "Verifying checkout..."
          ls -la
          
          if [ -f "package.json" ]; then
            echo "✅ Found package.json - code checkout successful"
            echo "Repository contents:"
            ls -la
          else
            echo "❌ package.json not found - checkout failed"
            echo "Current directory: $(pwd)"
            echo "Contents:"
            ls -la
            exit 1
          fi
          
          # Show git information
          echo "Git information:"
          git log --oneline -1
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Setup Node.js
        run: |
          # Install Node.js 20 using NodeSource repository
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if test script exists)
        run: npm test || echo "No tests configured yet"
        continue-on-error: true

  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]
    if: gitea.event_name == 'push' && (gitea.ref == 'refs/heads/main' || gitea.ref == 'refs/heads/develop')
    steps:
      - name: Checkout code
        run: |
          # Install git and clone the repository
          echo "Installing git..."
          apt-get update && apt-get install -y git
          
          echo "Cloning repository..."
          git clone https://gitea.dredre.net/dre/go-transit-group.git .
          
          echo "Checking out commit: ${{ gitea.sha }}"
          git checkout ${{ gitea.sha }}
          
          # Verify we have the expected files
          echo "Verifying checkout..."
          ls -la
          
          if [ -f "package.json" ]; then
            echo "✅ Found package.json - code checkout successful"
            echo "Repository contents:"
            ls -la
          else
            echo "❌ package.json not found - checkout failed"
            echo "Current directory: $(pwd)"
            echo "Contents:"
            ls -la
            exit 1
          fi
          
          # Show git information
          echo "Git information:"
          git log --oneline -1
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: docker-build
    if: gitea.ref == 'refs/heads/develop'
    environment:
      name: development
      url: https://dev.go-transit.dredre.net
    steps:
      - name: Deploy to dev environment
        run: |
          echo "Deploying to development environment..."
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop-${{ github.sha }}"
          # Add actual deployment commands here (e.g., kubectl, docker-compose, etc.)

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: docker-build
    if: gitea.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://go-transit.dredre.net
    steps:
      - name: Deploy to production environment
        run: |
          echo "Deploying to production environment..."
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          # Add actual deployment commands here

  notify-completion:
    name: Notify Workflow Completion
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, build, test, docker-build]
    if: always()
    steps:
      - name: Workflow completion notification
        run: |
          if [ "${{ needs.lint-and-typecheck.result }}" == "success" ] && 
             [ "${{ needs.build.result }}" == "success" ] && 
             [ "${{ needs.test.result }}" == "success" ] && 
             [ "${{ needs.docker-build.result }}" == "success" ]; then
            echo "✅ Workflow completed successfully!"
            echo "Repository: ${{ gitea.repository }}"
            echo "Branch: ${{ gitea.ref_name }}"
            echo "Commit: ${{ gitea.sha }}"
            echo "Workflow: ${{ gitea.workflow }}"
            echo "Run ID: ${{ gitea.run_id }}"
          else
            echo "❌ Workflow failed!"
            echo "Lint: ${{ needs.lint-and-typecheck.result }}"
            echo "Build: ${{ needs.build.result }}"
            echo "Test: ${{ needs.test.result }}"
            echo "Docker: ${{ needs.docker-build.result }}"
            echo "Repository: ${{ gitea.repository }}"
            echo "Branch: ${{ gitea.ref_name }}"
            echo "Commit: ${{ gitea.sha }}"
          fi
