/** AUTOGENERATED FILE - DO NOT EDIT
 * This file was generated by running 'supabase gen types typescript --local' */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      agency: {
        Row: {
          agency_id: string;
          agency_lang: string | null;
          agency_name: string;
          agency_phone: string | null;
          agency_timezone: string;
          agency_url: string;
        };
        Insert: {
          agency_id: string;
          agency_lang?: string | null;
          agency_name: string;
          agency_phone?: string | null;
          agency_timezone: string;
          agency_url: string;
        };
        Update: {
          agency_id?: string;
          agency_lang?: string | null;
          agency_name?: string;
          agency_phone?: string | null;
          agency_timezone?: string;
          agency_url?: string;
        };
        Relationships: [];
      };
      calendar: {
        Row: {
          end_date: string;
          friday: boolean;
          monday: boolean;
          saturday: boolean;
          service_id: string;
          start_date: string;
          sunday: boolean;
          thursday: boolean;
          tuesday: boolean;
          wednesday: boolean;
        };
        Insert: {
          end_date: string;
          friday: boolean;
          monday: boolean;
          saturday: boolean;
          service_id: string;
          start_date: string;
          sunday: boolean;
          thursday: boolean;
          tuesday: boolean;
          wednesday: boolean;
        };
        Update: {
          end_date?: string;
          friday?: boolean;
          monday?: boolean;
          saturday?: boolean;
          service_id?: string;
          start_date?: string;
          sunday?: boolean;
          thursday?: boolean;
          tuesday?: boolean;
          wednesday?: boolean;
        };
        Relationships: [];
      };
      calendar_dates: {
        Row: {
          date: string;
          exception_type: number;
          service_id: string;
        };
        Insert: {
          date: string;
          exception_type: number;
          service_id: string;
        };
        Update: {
          date?: string;
          exception_type?: number;
          service_id?: string;
        };
        Relationships: [];
      };
      mikro_orm_migrations: {
        Row: {
          executed_at: string | null;
          id: number;
          name: string | null;
        };
        Insert: {
          executed_at?: string | null;
          id?: number;
          name?: string | null;
        };
        Update: {
          executed_at?: string | null;
          id?: number;
          name?: string | null;
        };
        Relationships: [];
      };
      routes: {
        Row: {
          agency_id: string | null;
          route_color: string | null;
          route_desc: string | null;
          route_id: string;
          route_long_name: string;
          route_short_name: string;
          route_text_color: string | null;
          route_type: number;
          route_url: string | null;
        };
        Insert: {
          agency_id?: string | null;
          route_color?: string | null;
          route_desc?: string | null;
          route_id: string;
          route_long_name: string;
          route_short_name: string;
          route_text_color?: string | null;
          route_type: number;
          route_url?: string | null;
        };
        Update: {
          agency_id?: string | null;
          route_color?: string | null;
          route_desc?: string | null;
          route_id?: string;
          route_long_name?: string;
          route_short_name?: string;
          route_text_color?: string | null;
          route_type?: number;
          route_url?: string | null;
        };
        Relationships: [];
      };
      stop_times: {
        Row: {
          arrival_time: string;
          departure_time: string;
          drop_off_type: number | null;
          pickup_type: number | null;
          shape_dist_traveled: number | null;
          stop_headsign: string | null;
          stop_id: string;
          stop_sequence: number;
          stop_stop_id: string;
          timepoint: number | null;
          trip_id: string;
          trip_trip_id: string;
        };
        Insert: {
          arrival_time: string;
          departure_time: string;
          drop_off_type?: number | null;
          pickup_type?: number | null;
          shape_dist_traveled?: number | null;
          stop_headsign?: string | null;
          stop_id: string;
          stop_sequence: number;
          stop_stop_id: string;
          timepoint?: number | null;
          trip_id: string;
          trip_trip_id: string;
        };
        Update: {
          arrival_time?: string;
          departure_time?: string;
          drop_off_type?: number | null;
          pickup_type?: number | null;
          shape_dist_traveled?: number | null;
          stop_headsign?: string | null;
          stop_id?: string;
          stop_sequence?: number;
          stop_stop_id?: string;
          timepoint?: number | null;
          trip_id?: string;
          trip_trip_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'stop_times_stop_stop_id_foreign';
            columns: ['stop_stop_id'];
            isOneToOne: false;
            referencedRelation: 'stops';
            referencedColumns: ['stop_id'];
          },
          {
            foreignKeyName: 'stop_times_trip_trip_id_foreign';
            columns: ['trip_trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['trip_id'];
          },
        ];
      };
      stops: {
        Row: {
          location_type: number | null;
          parent_station: string | null;
          stop_desc: string | null;
          stop_id: string;
          stop_lat: number;
          stop_lon: number;
          stop_name: string;
          stop_url: string | null;
          wheelchair_boarding: number | null;
          zone_id: string | null;
        };
        Insert: {
          location_type?: number | null;
          parent_station?: string | null;
          stop_desc?: string | null;
          stop_id: string;
          stop_lat: number;
          stop_lon: number;
          stop_name: string;
          stop_url?: string | null;
          wheelchair_boarding?: number | null;
          zone_id?: string | null;
        };
        Update: {
          location_type?: number | null;
          parent_station?: string | null;
          stop_desc?: string | null;
          stop_id?: string;
          stop_lat?: number;
          stop_lon?: number;
          stop_name?: string;
          stop_url?: string | null;
          wheelchair_boarding?: number | null;
          zone_id?: string | null;
        };
        Relationships: [];
      };
      trips: {
        Row: {
          bikes_allowed: number | null;
          block_id: string | null;
          direction_id: number | null;
          route_id: string;
          route_route_id: string;
          service_id: string;
          shape_id: string | null;
          trip_headsign: string | null;
          trip_id: string;
          trip_short_name: string | null;
          wheelchair_accessible: number | null;
        };
        Insert: {
          bikes_allowed?: number | null;
          block_id?: string | null;
          direction_id?: number | null;
          route_id: string;
          route_route_id: string;
          service_id: string;
          shape_id?: string | null;
          trip_headsign?: string | null;
          trip_id: string;
          trip_short_name?: string | null;
          wheelchair_accessible?: number | null;
        };
        Update: {
          bikes_allowed?: number | null;
          block_id?: string | null;
          direction_id?: number | null;
          route_id?: string;
          route_route_id?: string;
          service_id?: string;
          shape_id?: string | null;
          trip_headsign?: string | null;
          trip_id?: string;
          trip_short_name?: string | null;
          wheelchair_accessible?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'trips_route_route_id_foreign';
            columns: ['route_route_id'];
            isOneToOne: false;
            referencedRelation: 'routes';
            referencedColumns: ['route_id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  'public'
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
